import { useLoaderData } from 'react-router';
import { client } from '~/sanity/client';
import type { AiInfo } from '~/lib/ai';
import Container from '~/components/Container';
import ItemCard from '~/components/ItemCard';

type Article = {
  title: string;
  slug: string;
  publishedAt: string | null;
  excerpt: string | null;
  tags: string[] | null;
  coverImage: { asset: object; alt: string } | null;
  ai: AiInfo | null;
};

export async function loader() {
  const articles: Article[] = await client.fetch(
    `*[_type == "article"] | order(publishedAt desc) {
      title,
      "slug": slug.current,
      publishedAt,
      excerpt,
      tags,
      coverImage { asset, alt },
      ai { designation, score }
    }`
  );
  return { articles };
}

export function meta() {
  return [{ title: 'Articles — EricDubé.com' }];
}

export default function Articles() {
  const { articles } = useLoaderData<typeof loader>();

  return (
    <Container style={{ paddingTop: '3rem', paddingBottom: '3rem' }}>
      <h1 style={{ fontSize: '2rem', marginBottom: '1.25rem' }}>Articles</h1>
      <aside
        style={{
          border: '1px solid rgba(192,132,252,0.35)',
          background: 'rgba(192,132,252,0.06)',
          borderRadius: '0.5rem',
          padding: '1rem 1.25rem',
          margin: '0 0 2rem',
          color: '#cbd5e1',
          fontSize: '0.9rem',
          lineHeight: 1.6,
        }}
      >
        My articles have mixed AI-involvement. My website is connected to an MCP server and sometimes
        I'll have Claude Code start out an article for me and edit it later. For this reason I'm using{' '}
        <a href="https://www.zerogpt.com" style={{ color: '#c084fc' }}>ZeroGPT</a> to highlight
        sentences likely generated by AI and provide an overall rating of AI involvement for each
        article.
      </aside>
      {articles.length === 0 && (
        <p style={{ color: '#94a3b8' }}>No articles yet.</p>
      )}
      <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '2rem' }}>
        {articles.map((article) => (
          <li key={article.slug}>
            <ItemCard {...article} url={`/articles/${article.slug}`} accentColor="var(--color-mustard)" />
          </li>
        ))}
      </ul>
    </Container>
  );
}
